version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: hacker_db
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - deploy_network
    container_name: hacker-db

  fastapi:
    build: backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - deploy_network
    container_name: hacker-fastapi

networks:
  deploy_network:
    driver: bridge